# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btnGo = QtWidgets.QPushButton(self.centralWidget)
        self.btnGo.setGeometry(QtCore.QRect(100, 480, 80, 60))
        self.btnGo.setObjectName("btnGo")
        self.btnShort = QtWidgets.QPushButton(self.centralWidget)
        self.btnShort.setGeometry(QtCore.QRect(300, 480, 80, 60))
        self.btnShort.setObjectName("btnShort")
        self.btnPassFail = QtWidgets.QPushButton(self.centralWidget)
        self.btnPassFail.setGeometry(QtCore.QRect(400, 480, 80, 60))
        self.btnPassFail.setObjectName("btnPassFail")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 781, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.brd5A = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd5A.sizePolicy().hasHeightForWidth())
        self.brd5A.setSizePolicy(sizePolicy)
        self.brd5A.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd5A.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd5A.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5A.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5A.setObjectName("brd5A")
        self.gridLayout.addWidget(self.brd5A, 4, 0, 1, 1)
        self.brd1D = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd1D.sizePolicy().hasHeightForWidth())
        self.brd1D.setSizePolicy(sizePolicy)
        self.brd1D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd1D.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd1D.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1D.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1D.setObjectName("brd1D")
        self.gridLayout.addWidget(self.brd1D, 0, 3, 1, 1)
        self.brd2A = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd2A.sizePolicy().hasHeightForWidth())
        self.brd2A.setSizePolicy(sizePolicy)
        self.brd2A.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd2A.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd2A.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2A.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2A.setObjectName("brd2A")
        self.gridLayout.addWidget(self.brd2A, 1, 0, 1, 1)
        self.brd4A = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd4A.sizePolicy().hasHeightForWidth())
        self.brd4A.setSizePolicy(sizePolicy)
        self.brd4A.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd4A.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd4A.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4A.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4A.setObjectName("brd4A")
        self.gridLayout.addWidget(self.brd4A, 3, 0, 1, 1)
        self.brd1B = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd1B.sizePolicy().hasHeightForWidth())
        self.brd1B.setSizePolicy(sizePolicy)
        self.brd1B.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd1B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd1B.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1B.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1B.setObjectName("brd1B")
        self.gridLayout.addWidget(self.brd1B, 0, 1, 1, 1)
        self.brd1E = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd1E.sizePolicy().hasHeightForWidth())
        self.brd1E.setSizePolicy(sizePolicy)
        self.brd1E.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd1E.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd1E.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1E.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1E.setObjectName("brd1E")
        self.gridLayout.addWidget(self.brd1E, 0, 4, 1, 1)
        self.brd1C = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd1C.sizePolicy().hasHeightForWidth())
        self.brd1C.setSizePolicy(sizePolicy)
        self.brd1C.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd1C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd1C.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1C.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1C.setObjectName("brd1C")
        self.gridLayout.addWidget(self.brd1C, 0, 2, 1, 1)
        self.brd1A = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd1A.sizePolicy().hasHeightForWidth())
        self.brd1A.setSizePolicy(sizePolicy)
        self.brd1A.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd1A.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd1A.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1A.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd1A.setBackgroundVisible(False)
        self.brd1A.setObjectName("brd1A")
        self.gridLayout.addWidget(self.brd1A, 0, 0, 1, 1)
        self.brd3A = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd3A.sizePolicy().hasHeightForWidth())
        self.brd3A.setSizePolicy(sizePolicy)
        self.brd3A.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd3A.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd3A.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3A.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3A.setObjectName("brd3A")
        self.gridLayout.addWidget(self.brd3A, 2, 0, 1, 1)
        self.brd2B = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd2B.sizePolicy().hasHeightForWidth())
        self.brd2B.setSizePolicy(sizePolicy)
        self.brd2B.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd2B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd2B.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2B.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2B.setObjectName("brd2B")
        self.gridLayout.addWidget(self.brd2B, 1, 1, 1, 1)
        self.brd2C = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd2C.sizePolicy().hasHeightForWidth())
        self.brd2C.setSizePolicy(sizePolicy)
        self.brd2C.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd2C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd2C.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2C.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2C.setObjectName("brd2C")
        self.gridLayout.addWidget(self.brd2C, 1, 2, 1, 1)
        self.brd2D = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd2D.sizePolicy().hasHeightForWidth())
        self.brd2D.setSizePolicy(sizePolicy)
        self.brd2D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd2D.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd2D.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2D.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2D.setObjectName("brd2D")
        self.gridLayout.addWidget(self.brd2D, 1, 3, 1, 1)
        self.brd2E = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd2E.sizePolicy().hasHeightForWidth())
        self.brd2E.setSizePolicy(sizePolicy)
        self.brd2E.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd2E.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd2E.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2E.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd2E.setObjectName("brd2E")
        self.gridLayout.addWidget(self.brd2E, 1, 4, 1, 1)
        self.brd3B = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd3B.sizePolicy().hasHeightForWidth())
        self.brd3B.setSizePolicy(sizePolicy)
        self.brd3B.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd3B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd3B.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3B.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3B.setObjectName("brd3B")
        self.gridLayout.addWidget(self.brd3B, 2, 1, 1, 1)
        self.brd3C = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd3C.sizePolicy().hasHeightForWidth())
        self.brd3C.setSizePolicy(sizePolicy)
        self.brd3C.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd3C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd3C.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3C.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3C.setObjectName("brd3C")
        self.gridLayout.addWidget(self.brd3C, 2, 2, 1, 1)
        self.brd3D = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd3D.sizePolicy().hasHeightForWidth())
        self.brd3D.setSizePolicy(sizePolicy)
        self.brd3D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd3D.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd3D.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3D.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3D.setObjectName("brd3D")
        self.gridLayout.addWidget(self.brd3D, 2, 3, 1, 1)
        self.brd3E = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd3E.sizePolicy().hasHeightForWidth())
        self.brd3E.setSizePolicy(sizePolicy)
        self.brd3E.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd3E.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd3E.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3E.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd3E.setObjectName("brd3E")
        self.gridLayout.addWidget(self.brd3E, 2, 4, 1, 1)
        self.brd4B = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd4B.sizePolicy().hasHeightForWidth())
        self.brd4B.setSizePolicy(sizePolicy)
        self.brd4B.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd4B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd4B.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4B.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4B.setObjectName("brd4B")
        self.gridLayout.addWidget(self.brd4B, 3, 1, 1, 1)
        self.brd5B = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd5B.sizePolicy().hasHeightForWidth())
        self.brd5B.setSizePolicy(sizePolicy)
        self.brd5B.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd5B.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd5B.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5B.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5B.setObjectName("brd5B")
        self.gridLayout.addWidget(self.brd5B, 4, 1, 1, 1)
        self.brd4C = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd4C.sizePolicy().hasHeightForWidth())
        self.brd4C.setSizePolicy(sizePolicy)
        self.brd4C.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd4C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd4C.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4C.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4C.setObjectName("brd4C")
        self.gridLayout.addWidget(self.brd4C, 3, 2, 1, 1)
        self.brd4D = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd4D.sizePolicy().hasHeightForWidth())
        self.brd4D.setSizePolicy(sizePolicy)
        self.brd4D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd4D.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd4D.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4D.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4D.setObjectName("brd4D")
        self.gridLayout.addWidget(self.brd4D, 3, 3, 1, 1)
        self.brd4E = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd4E.sizePolicy().hasHeightForWidth())
        self.brd4E.setSizePolicy(sizePolicy)
        self.brd4E.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd4E.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd4E.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4E.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd4E.setObjectName("brd4E")
        self.gridLayout.addWidget(self.brd4E, 3, 4, 1, 1)
        self.brd5C = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd5C.sizePolicy().hasHeightForWidth())
        self.brd5C.setSizePolicy(sizePolicy)
        self.brd5C.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd5C.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd5C.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5C.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5C.setObjectName("brd5C")
        self.gridLayout.addWidget(self.brd5C, 4, 2, 1, 1)
        self.brd5D = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd5D.sizePolicy().hasHeightForWidth())
        self.brd5D.setSizePolicy(sizePolicy)
        self.brd5D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd5D.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd5D.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5D.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5D.setObjectName("brd5D")
        self.gridLayout.addWidget(self.brd5D, 4, 3, 1, 1)
        self.brd5E = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brd5E.sizePolicy().hasHeightForWidth())
        self.brd5E.setSizePolicy(sizePolicy)
        self.brd5E.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brd5E.setFrameShadow(QtWidgets.QFrame.Plain)
        self.brd5E.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5E.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brd5E.setObjectName("brd5E")
        self.gridLayout.addWidget(self.brd5E, 4, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuBackbone_Tester = QtWidgets.QMenu(self.menuBar)
        self.menuBackbone_Tester.setObjectName("menuBackbone_Tester")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuBackbone_Tester.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGo.setText(_translate("MainWindow", "Start"))
        self.btnShort.setText(_translate("MainWindow", "Short Check"))
        self.btnPassFail.setText(_translate("MainWindow", "Pass/Fail"))
        self.menuBackbone_Tester.setTitle(_translate("MainWindow", "Backbone Tester"))

